# Generated by Django 3.0.4 on 2021-01-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
